[2025-03-25T19:30:01.733+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T19:30:01.766+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_roadkill.get_all_data scheduled__2025-03-25T19:00:00+00:00 [queued]>
[2025-03-25T19:30:01.785+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_roadkill.get_all_data scheduled__2025-03-25T19:00:00+00:00 [queued]>
[2025-03-25T19:30:01.786+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2025-03-25T19:30:01.796+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_all_data> on 2025-03-25 19:00:00+00:00
[2025-03-25T19:30:01.808+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=106) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T19:30:01.810+0000] {standard_task_runner.py:72} INFO - Started process 112 to run task
[2025-03-25T19:30:01.809+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_roadkill', 'get_all_data', 'scheduled__2025-03-25T19:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmp4ih73k14']
[2025-03-25T19:30:01.813+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask get_all_data
[2025-03-25T19:30:01.924+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_roadkill.get_all_data scheduled__2025-03-25T19:00:00+00:00 [running]> on host 5433644a7716
[2025-03-25T19:30:01.998+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_roadkill' AIRFLOW_CTX_TASK_ID='get_all_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-25T19:00:00+00:00'
[2025-03-25T19:30:02.004+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-25T19:30:02.008+0000] {inaturalist_dag.py:150} INFO - Getting data from keyword: roadkill
[2025-03-25T19:30:02.031+0000] {inaturalist_dag.py:41} INFO - Maximum id 13459001 for the request
[2025-03-25T19:30:11.710+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:30:12.022+0000] {inaturalist_dag.py:163} INFO - Extracted 200 observations
[2025-03-25T19:30:12.034+0000] {inaturalist_dag.py:41} INFO - Maximum id 14754609 for the request
[2025-03-25T19:30:23.159+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:30:23.266+0000] {inaturalist_dag.py:163} INFO - Extracted 399 observations
[2025-03-25T19:30:23.267+0000] {inaturalist_dag.py:41} INFO - Maximum id 16271445 for the request
[2025-03-25T19:30:35.328+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:30:35.347+0000] {inaturalist_dag.py:163} INFO - Extracted 599 observations
[2025-03-25T19:30:35.348+0000] {inaturalist_dag.py:41} INFO - Maximum id 17779186 for the request
[2025-03-25T19:30:44.598+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:30:44.616+0000] {inaturalist_dag.py:163} INFO - Extracted 795 observations
[2025-03-25T19:30:44.617+0000] {inaturalist_dag.py:41} INFO - Maximum id 19091392 for the request
[2025-03-25T19:30:54.078+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:30:54.094+0000] {inaturalist_dag.py:163} INFO - Extracted 994 observations
[2025-03-25T19:30:54.094+0000] {inaturalist_dag.py:41} INFO - Maximum id 19708416 for the request
[2025-03-25T19:30:57.637+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:30:57.662+0000] {inaturalist_dag.py:163} INFO - Extracted 1194 observations
[2025-03-25T19:30:57.662+0000] {inaturalist_dag.py:41} INFO - Maximum id 19728241 for the request
[2025-03-25T19:31:04.406+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:31:04.453+0000] {inaturalist_dag.py:163} INFO - Extracted 1394 observations
[2025-03-25T19:31:04.454+0000] {inaturalist_dag.py:41} INFO - Maximum id 19740778 for the request
[2025-03-25T19:31:09.090+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:31:09.150+0000] {inaturalist_dag.py:163} INFO - Extracted 1593 observations
[2025-03-25T19:31:09.152+0000] {inaturalist_dag.py:41} INFO - Maximum id 19760409 for the request
[2025-03-25T19:31:12.828+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:31:12.862+0000] {inaturalist_dag.py:163} INFO - Extracted 1793 observations
[2025-03-25T19:31:12.863+0000] {inaturalist_dag.py:41} INFO - Maximum id 19770188 for the request
[2025-03-25T19:31:20.186+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:31:20.201+0000] {inaturalist_dag.py:163} INFO - Extracted 1993 observations
[2025-03-25T19:31:20.202+0000] {inaturalist_dag.py:41} INFO - Maximum id 19787415 for the request
[2025-03-25T19:31:28.751+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:31:28.766+0000] {inaturalist_dag.py:163} INFO - Extracted 2193 observations
[2025-03-25T19:31:28.766+0000] {inaturalist_dag.py:41} INFO - Maximum id 19815550 for the request
[2025-03-25T19:31:38.022+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:31:38.034+0000] {inaturalist_dag.py:163} INFO - Extracted 2393 observations
[2025-03-25T19:31:38.034+0000] {inaturalist_dag.py:41} INFO - Maximum id 19861048 for the request
[2025-03-25T19:31:49.026+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:31:49.042+0000] {inaturalist_dag.py:163} INFO - Extracted 2593 observations
[2025-03-25T19:31:49.042+0000] {inaturalist_dag.py:41} INFO - Maximum id 19883023 for the request
[2025-03-25T19:31:59.716+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:31:59.729+0000] {inaturalist_dag.py:163} INFO - Extracted 2793 observations
[2025-03-25T19:31:59.729+0000] {inaturalist_dag.py:41} INFO - Maximum id 19940980 for the request
[2025-03-25T19:32:05.770+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:32:05.779+0000] {inaturalist_dag.py:163} INFO - Extracted 2993 observations
[2025-03-25T19:32:05.780+0000] {inaturalist_dag.py:41} INFO - Maximum id 19981489 for the request
[2025-03-25T19:32:13.249+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:32:13.262+0000] {inaturalist_dag.py:163} INFO - Extracted 3193 observations
[2025-03-25T19:32:13.263+0000] {inaturalist_dag.py:41} INFO - Maximum id 20040448 for the request
[2025-03-25T19:32:19.886+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:32:19.894+0000] {inaturalist_dag.py:163} INFO - Extracted 3393 observations
[2025-03-25T19:32:19.895+0000] {inaturalist_dag.py:41} INFO - Maximum id 20052082 for the request
[2025-03-25T19:32:26.491+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:32:26.501+0000] {inaturalist_dag.py:163} INFO - Extracted 3593 observations
[2025-03-25T19:32:26.502+0000] {inaturalist_dag.py:41} INFO - Maximum id 20069923 for the request
[2025-03-25T19:32:34.568+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T19:32:34.594+0000] {inaturalist_dag.py:163} INFO - Extracted 3793 observations
[2025-03-25T19:32:34.594+0000] {inaturalist_dag.py:41} INFO - Maximum id 20240271 for the request
[2025-03-25T19:32:35.448+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 155, in get_all_data
    last_observation_id, observations_extracted = get_data(maximum_id, api_url)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 53, in get_data
    response = requests.get(api_url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-03-25T19:32:35.484+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=get_inaturalist_data_roadkill, task_id=get_all_data, run_id=scheduled__2025-03-25T19:00:00+00:00, execution_date=20250325T190000, start_date=20250325T193001, end_date=20250325T193235
[2025-03-25T19:32:35.505+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-25T19:32:35.506+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 43 for task get_all_data (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')); 112)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 155, in get_all_data
    last_observation_id, observations_extracted = get_data(maximum_id, api_url)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 53, in get_data
    response = requests.get(api_url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-03-25T19:32:35.562+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T19:32:35.590+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T19:32:35.591+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
