[2025-03-27T14:47:34.287+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T14:47:34.546+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_roadkill.get_all_data manual__2025-03-27T14:47:31.171769+00:00 [queued]>
[2025-03-27T14:47:34.589+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_roadkill.get_all_data manual__2025-03-27T14:47:31.171769+00:00 [queued]>
[2025-03-27T14:47:34.591+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2025-03-27T14:47:34.715+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_all_data> on 2025-03-27 14:47:31.171769+00:00
[2025-03-27T14:47:34.731+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=179) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T14:47:34.732+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_roadkill', 'get_all_data', 'manual__2025-03-27T14:47:31.171769+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmp04f14ef0']
[2025-03-27T14:47:34.740+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask get_all_data
[2025-03-27T14:47:34.741+0000] {standard_task_runner.py:72} INFO - Started process 181 to run task
[2025-03-27T14:47:35.404+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_roadkill.get_all_data manual__2025-03-27T14:47:31.171769+00:00 [running]> on host f05f38f172ca
[2025-03-27T14:47:36.394+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_roadkill' AIRFLOW_CTX_TASK_ID='get_all_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T14:47:31.171769+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T14:47:31.171769+00:00'
[2025-03-27T14:47:36.398+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T14:47:36.407+0000] {inaturalist_dag.py:150} INFO - Getting data from keyword: roadkill
[2025-03-27T14:47:36.630+0000] {inaturalist_dag.py:41} INFO - Maximum id 1 for the request
[2025-03-27T14:47:39.764+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:47:39.779+0000] {inaturalist_dag.py:163} INFO - Extracted 193 observations
[2025-03-27T14:47:39.779+0000] {inaturalist_dag.py:41} INFO - Maximum id 391838 for the request
[2025-03-27T14:47:41.712+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:47:41.721+0000] {inaturalist_dag.py:163} INFO - Extracted 386 observations
[2025-03-27T14:47:41.722+0000] {inaturalist_dag.py:41} INFO - Maximum id 921584 for the request
[2025-03-27T14:47:42.966+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:47:42.969+0000] {inaturalist_dag.py:163} INFO - Extracted 581 observations
[2025-03-27T14:47:42.970+0000] {inaturalist_dag.py:41} INFO - Maximum id 926875 for the request
[2025-03-27T14:47:44.985+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:47:44.995+0000] {inaturalist_dag.py:163} INFO - Extracted 758 observations
[2025-03-27T14:47:44.995+0000] {inaturalist_dag.py:41} INFO - Maximum id 1122856 for the request
[2025-03-27T14:47:48.083+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:47:48.105+0000] {inaturalist_dag.py:163} INFO - Extracted 954 observations
[2025-03-27T14:47:48.105+0000] {inaturalist_dag.py:41} INFO - Maximum id 1673455 for the request
[2025-03-27T14:47:54.129+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:47:54.166+0000] {inaturalist_dag.py:163} INFO - Extracted 1148 observations
[2025-03-27T14:47:54.167+0000] {inaturalist_dag.py:41} INFO - Maximum id 2496524 for the request
[2025-03-27T14:48:05.478+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:05.514+0000] {inaturalist_dag.py:163} INFO - Extracted 1343 observations
[2025-03-27T14:48:05.514+0000] {inaturalist_dag.py:41} INFO - Maximum id 3075819 for the request
[2025-03-27T14:48:08.279+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:08.296+0000] {inaturalist_dag.py:163} INFO - Extracted 1535 observations
[2025-03-27T14:48:08.296+0000] {inaturalist_dag.py:41} INFO - Maximum id 4166723 for the request
[2025-03-27T14:48:10.740+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:10.760+0000] {inaturalist_dag.py:163} INFO - Extracted 1729 observations
[2025-03-27T14:48:10.760+0000] {inaturalist_dag.py:41} INFO - Maximum id 5327081 for the request
[2025-03-27T14:48:14.584+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:14.606+0000] {inaturalist_dag.py:163} INFO - Extracted 1924 observations
[2025-03-27T14:48:14.608+0000] {inaturalist_dag.py:41} INFO - Maximum id 6652806 for the request
[2025-03-27T14:48:16.920+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:16.936+0000] {inaturalist_dag.py:163} INFO - Extracted 2121 observations
[2025-03-27T14:48:16.936+0000] {inaturalist_dag.py:41} INFO - Maximum id 7760935 for the request
[2025-03-27T14:48:18.412+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:18.425+0000] {inaturalist_dag.py:163} INFO - Extracted 2301 observations
[2025-03-27T14:48:18.426+0000] {inaturalist_dag.py:41} INFO - Maximum id 7797273 for the request
[2025-03-27T14:48:19.936+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:19.945+0000] {inaturalist_dag.py:163} INFO - Extracted 2488 observations
[2025-03-27T14:48:19.945+0000] {inaturalist_dag.py:41} INFO - Maximum id 7797483 for the request
[2025-03-27T14:48:21.468+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:21.477+0000] {inaturalist_dag.py:163} INFO - Extracted 2682 observations
[2025-03-27T14:48:21.477+0000] {inaturalist_dag.py:41} INFO - Maximum id 7797703 for the request
[2025-03-27T14:48:22.932+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:22.937+0000] {inaturalist_dag.py:163} INFO - Extracted 2871 observations
[2025-03-27T14:48:22.937+0000] {inaturalist_dag.py:41} INFO - Maximum id 7797923 for the request
[2025-03-27T14:48:24.398+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:24.403+0000] {inaturalist_dag.py:163} INFO - Extracted 3047 observations
[2025-03-27T14:48:24.404+0000] {inaturalist_dag.py:41} INFO - Maximum id 7814098 for the request
[2025-03-27T14:48:25.930+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:25.933+0000] {inaturalist_dag.py:163} INFO - Extracted 3228 observations
[2025-03-27T14:48:25.933+0000] {inaturalist_dag.py:41} INFO - Maximum id 7814315 for the request
[2025-03-27T14:48:27.347+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:27.352+0000] {inaturalist_dag.py:163} INFO - Extracted 3414 observations
[2025-03-27T14:48:27.352+0000] {inaturalist_dag.py:41} INFO - Maximum id 7814532 for the request
[2025-03-27T14:48:28.834+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:28.846+0000] {inaturalist_dag.py:163} INFO - Extracted 3613 observations
[2025-03-27T14:48:28.850+0000] {inaturalist_dag.py:41} INFO - Maximum id 7814772 for the request
[2025-03-27T14:48:30.589+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T14:48:30.615+0000] {inaturalist_dag.py:163} INFO - Extracted 3787 observations
[2025-03-27T14:48:30.636+0000] {inaturalist_dag.py:41} INFO - Maximum id 7814992 for the request
[2025-03-27T14:48:37.088+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 155, in get_all_data
    last_observation_id, observations_extracted = get_data(maximum_id, api_url)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 53, in get_data
    response = requests.get(api_url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-03-27T14:48:49.434+0000] {job.py:229} INFO - Heartbeat recovered after 23.70 seconds
[2025-03-27T14:48:49.707+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=get_inaturalist_data_roadkill, task_id=get_all_data, run_id=manual__2025-03-27T14:47:31.171769+00:00, execution_date=20250327T144731, start_date=20250327T144734, end_date=20250327T144849
[2025-03-27T14:48:49.845+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T14:48:49.846+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 51 for task get_all_data (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')); 181)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 155, in get_all_data
    last_observation_id, observations_extracted = get_data(maximum_id, api_url)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 53, in get_data
    response = requests.get(api_url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-03-27T14:48:50.142+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T14:48:50.257+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
