[2025-03-27T17:31:45.562+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T17:31:47.753+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelada.test_minio_upload scheduled__2025-03-27T17:00:00+00:00 [queued]>
[2025-03-27T17:31:48.832+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelada.test_minio_upload scheduled__2025-03-27T17:00:00+00:00 [queued]>
[2025-03-27T17:31:48.940+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-27T17:31:50.800+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): test_minio_upload> on 2025-03-27 17:00:00+00:00
[2025-03-27T17:31:51.515+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_atropelada', 'test_minio_upload', 'scheduled__2025-03-27T17:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmpuzw7ouik']
[2025-03-27T17:31:51.532+0000] {standard_task_runner.py:105} INFO - Job 194: Subtask test_minio_upload
[2025-03-27T17:31:51.490+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=490) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T17:31:51.570+0000] {standard_task_runner.py:72} INFO - Started process 513 to run task
[2025-03-27T17:31:59.465+0000] {job.py:229} INFO - Heartbeat recovered after 55.60 seconds
[2025-03-27T17:32:02.401+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_atropelada.test_minio_upload scheduled__2025-03-27T17:00:00+00:00 [running]> on host 804b404afff8
[2025-03-27T17:32:42.182+0000] {job.py:229} INFO - Heartbeat recovered after 43.00 seconds
[2025-03-27T17:32:53.594+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_atropelada' AIRFLOW_CTX_TASK_ID='test_minio_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T17:00:00+00:00'
[2025-03-27T17:32:54.230+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T17:32:54.729+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 470, in test_minio_upload
    connector = MinioConnector(url=minio_url, access_key=access_key, secret_key=secret_key, bucket_name=bucket_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/connectors/minio.py", line 20, in __init__
    self.client = Minio(
                  ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 152, in __init__
    self._base_url = BaseURL(
                     ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/helpers.py", line 551, in __init__
    url = _parse_url(endpoint)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/helpers.py", line 512, in _parse_url
    raise ValueError("path in endpoint is not allowed")
ValueError: path in endpoint is not allowed
[2025-03-27T17:33:09.747+0000] {job.py:229} INFO - Heartbeat recovered after 18.21 seconds
[2025-03-27T17:33:10.369+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=get_inaturalist_data_atropelada, task_id=test_minio_upload, run_id=scheduled__2025-03-27T17:00:00+00:00, execution_date=20250327T170000, start_date=20250327T173147, end_date=20250327T173310
[2025-03-27T17:33:12.795+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T17:33:12.950+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 194 for task test_minio_upload (path in endpoint is not allowed; 513)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 470, in test_minio_upload
    connector = MinioConnector(url=minio_url, access_key=access_key, secret_key=secret_key, bucket_name=bucket_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/connectors/minio.py", line 20, in __init__
    self.client = Minio(
                  ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/api.py", line 152, in __init__
    self._base_url = BaseURL(
                     ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/helpers.py", line 551, in __init__
    url = _parse_url(endpoint)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/minio/helpers.py", line 512, in _parse_url
    raise ValueError("path in endpoint is not allowed")
ValueError: path in endpoint is not allowed
[2025-03-27T17:33:13.708+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T17:33:14.329+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T17:33:14.449+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-27T17:33:14.620+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
