[2025-03-27T15:01:27.141+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T15:01:27.194+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_roadkill.get_all_data scheduled__2025-03-27T14:30:00+00:00 [queued]>
[2025-03-27T15:01:27.219+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_roadkill.get_all_data scheduled__2025-03-27T14:30:00+00:00 [queued]>
[2025-03-27T15:01:27.221+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2025-03-27T15:01:27.294+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_all_data> on 2025-03-27 14:30:00+00:00
[2025-03-27T15:01:27.318+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=67) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T15:01:27.322+0000] {standard_task_runner.py:72} INFO - Started process 75 to run task
[2025-03-27T15:01:27.322+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_roadkill', 'get_all_data', 'scheduled__2025-03-27T14:30:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmpyas78zba']
[2025-03-27T15:01:27.331+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask get_all_data
[2025-03-27T15:01:27.592+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_roadkill.get_all_data scheduled__2025-03-27T14:30:00+00:00 [running]> on host 75fbd25ffde3
[2025-03-27T15:01:27.932+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_roadkill' AIRFLOW_CTX_TASK_ID='get_all_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T14:30:00+00:00'
[2025-03-27T15:01:27.936+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T15:01:27.940+0000] {inaturalist_dag.py:150} INFO - Getting data from keyword: roadkill
[2025-03-27T15:01:27.971+0000] {inaturalist_dag.py:41} INFO - Maximum id 54090476 for the request
[2025-03-27T15:01:36.089+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:01:36.196+0000] {inaturalist_dag.py:163} INFO - Extracted 200 observations
[2025-03-27T15:01:36.200+0000] {inaturalist_dag.py:41} INFO - Maximum id 58289772 for the request
[2025-03-27T15:01:45.692+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:01:45.771+0000] {inaturalist_dag.py:163} INFO - Extracted 400 observations
[2025-03-27T15:01:45.772+0000] {inaturalist_dag.py:41} INFO - Maximum id 61872184 for the request
[2025-03-27T15:01:53.273+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:01:53.389+0000] {inaturalist_dag.py:163} INFO - Extracted 600 observations
[2025-03-27T15:01:53.391+0000] {inaturalist_dag.py:41} INFO - Maximum id 64974165 for the request
[2025-03-27T15:02:01.814+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:01.855+0000] {inaturalist_dag.py:163} INFO - Extracted 800 observations
[2025-03-27T15:02:01.857+0000] {inaturalist_dag.py:41} INFO - Maximum id 66365717 for the request
[2025-03-27T15:02:07.207+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:07.248+0000] {inaturalist_dag.py:163} INFO - Extracted 1000 observations
[2025-03-27T15:02:07.250+0000] {inaturalist_dag.py:41} INFO - Maximum id 66680729 for the request
[2025-03-27T15:02:13.377+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:13.400+0000] {inaturalist_dag.py:163} INFO - Extracted 1200 observations
[2025-03-27T15:02:13.401+0000] {inaturalist_dag.py:41} INFO - Maximum id 66995293 for the request
[2025-03-27T15:02:18.789+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:18.821+0000] {inaturalist_dag.py:163} INFO - Extracted 1400 observations
[2025-03-27T15:02:18.823+0000] {inaturalist_dag.py:41} INFO - Maximum id 67475373 for the request
[2025-03-27T15:02:25.163+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:25.251+0000] {inaturalist_dag.py:163} INFO - Extracted 1600 observations
[2025-03-27T15:02:25.252+0000] {inaturalist_dag.py:41} INFO - Maximum id 67819834 for the request
[2025-03-27T15:02:30.295+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:30.327+0000] {inaturalist_dag.py:163} INFO - Extracted 1800 observations
[2025-03-27T15:02:30.328+0000] {inaturalist_dag.py:41} INFO - Maximum id 68254531 for the request
[2025-03-27T15:02:35.493+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:35.544+0000] {inaturalist_dag.py:163} INFO - Extracted 2000 observations
[2025-03-27T15:02:35.548+0000] {inaturalist_dag.py:41} INFO - Maximum id 68670290 for the request
[2025-03-27T15:02:40.281+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:40.344+0000] {inaturalist_dag.py:163} INFO - Extracted 2200 observations
[2025-03-27T15:02:40.351+0000] {inaturalist_dag.py:41} INFO - Maximum id 68715056 for the request
[2025-03-27T15:02:45.717+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:45.778+0000] {inaturalist_dag.py:163} INFO - Extracted 2400 observations
[2025-03-27T15:02:45.780+0000] {inaturalist_dag.py:41} INFO - Maximum id 68842679 for the request
[2025-03-27T15:02:50.454+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:50.511+0000] {inaturalist_dag.py:163} INFO - Extracted 2600 observations
[2025-03-27T15:02:50.513+0000] {inaturalist_dag.py:41} INFO - Maximum id 68875523 for the request
[2025-03-27T15:02:54.350+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:54.411+0000] {inaturalist_dag.py:163} INFO - Extracted 2800 observations
[2025-03-27T15:02:54.415+0000] {inaturalist_dag.py:41} INFO - Maximum id 68979538 for the request
[2025-03-27T15:02:59.566+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:02:59.604+0000] {inaturalist_dag.py:163} INFO - Extracted 3000 observations
[2025-03-27T15:02:59.608+0000] {inaturalist_dag.py:41} INFO - Maximum id 69035682 for the request
[2025-03-27T15:03:05.183+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:03:05.221+0000] {inaturalist_dag.py:163} INFO - Extracted 3200 observations
[2025-03-27T15:03:05.222+0000] {inaturalist_dag.py:41} INFO - Maximum id 69039122 for the request
[2025-03-27T15:03:11.245+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:03:11.314+0000] {inaturalist_dag.py:163} INFO - Extracted 3400 observations
[2025-03-27T15:03:11.315+0000] {inaturalist_dag.py:41} INFO - Maximum id 69161820 for the request
[2025-03-27T15:03:15.552+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:03:15.634+0000] {inaturalist_dag.py:163} INFO - Extracted 3600 observations
[2025-03-27T15:03:15.636+0000] {inaturalist_dag.py:41} INFO - Maximum id 69383869 for the request
[2025-03-27T15:03:20.669+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:03:20.802+0000] {inaturalist_dag.py:163} INFO - Extracted 3800 observations
[2025-03-27T15:03:20.845+0000] {inaturalist_dag.py:41} INFO - Maximum id 69446935 for the request
[2025-03-27T15:03:40.470+0000] {job.py:229} INFO - Heartbeat recovered after 19.96 seconds
[2025-03-27T15:03:41.080+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-27T15:03:41.699+0000] {inaturalist_dag.py:163} INFO - Extracted 4000 observations
[2025-03-27T15:03:41.804+0000] {inaturalist_dag.py:41} INFO - Maximum id 69532306 for the request
[2025-03-27T15:03:45.366+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.inaturalist.org', port=443): Max retries exceeded with url: /v1/observations?geo=true&iconic_taxa=Amphibia%2CAves%2CMammalia%2CReptilia%2Cunknown&id_above=69532306&q=roadkill&page=1&per_page=200&order=asc&order_by=id (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 155, in get_all_data
    last_observation_id, observations_extracted = get_data(maximum_id, api_url)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 53, in get_data
    response = requests.get(api_url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.inaturalist.org', port=443): Max retries exceeded with url: /v1/observations?geo=true&iconic_taxa=Amphibia%2CAves%2CMammalia%2CReptilia%2Cunknown&id_above=69532306&q=roadkill&page=1&per_page=200&order=asc&order_by=id (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
[2025-03-27T15:04:27.887+0000] {job.py:229} INFO - Heartbeat recovered after 47.71 seconds
[2025-03-27T15:04:28.039+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=get_inaturalist_data_roadkill, task_id=get_all_data, run_id=scheduled__2025-03-27T14:30:00+00:00, execution_date=20250327T143000, start_date=20250327T150127, end_date=20250327T150428
[2025-03-27T15:04:33.414+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T15:04:33.497+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 72 for task get_all_data (HTTPSConnectionPool(host='api.inaturalist.org', port=443): Max retries exceeded with url: /v1/observations?geo=true&iconic_taxa=Amphibia%2CAves%2CMammalia%2CReptilia%2Cunknown&id_above=69532306&q=roadkill&page=1&per_page=200&order=asc&order_by=id (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))); 75)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.inaturalist.org', port=443): Max retries exceeded with url: /v1/observations?geo=true&iconic_taxa=Amphibia%2CAves%2CMammalia%2CReptilia%2Cunknown&id_above=69532306&q=roadkill&page=1&per_page=200&order=asc&order_by=id (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 155, in get_all_data
    last_observation_id, observations_extracted = get_data(maximum_id, api_url)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 53, in get_data
    response = requests.get(api_url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.inaturalist.org', port=443): Max retries exceeded with url: /v1/observations?geo=true&iconic_taxa=Amphibia%2CAves%2CMammalia%2CReptilia%2Cunknown&id_above=69532306&q=roadkill&page=1&per_page=200&order=asc&order_by=id (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
[2025-03-27T15:04:34.027+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T15:04:34.609+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T15:04:34.686+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-27T15:04:35.164+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
